baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Markus van Duijn | Profile'
theme = "toha"

[params]
background = "images/site/default-background.jpg"
darkBackground = "images/site/default-background.jpg" # optioneel voor dark mode

[params.logo]
favicon = "images/site/favicon.png"